services:
  openvpn:
    image: dperson/openvpn-client:latest
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    volumes:
      - /mnt/TrueNAS/Applications/openvpn:/vpn
      - /mnt/TrueNAS/Applications/openvpn/logs:/var/log/openvpn
    environment:
      - TZ=Europe/London
      - OPENVPN_CONFIG=uk2507.nordvpn.com.udp.ovpn
      #- DNS=1.1.1.1,8.8.8.8
    ports:
      # <── expose ports here
      - 8080:8080 # qBittorrent WebUI
      #- 6881:6881 # Torrent TCP
      #- 6881:6881/udp # Torrent UDP
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - openvpn
    network_mode: service:openvpn # shares OpenVPN’s stack
    restart: unless-stopped
    volumes:
      - /mnt/TrueNAS/Applications/qbittorrent:/config
      - /mnt/TrueNAS/Media/Downloads:/Downloads
      - /mnt/TrueNAS/Media/Movies:/Movies
      - /mnt/TrueNAS/Media/Shows:/Shows
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - WEBUI_PORT=8080
networks: {}
